### ISSUE TITLE
Registry should provide FindMetrics functionality

### ISSUE THREAD

**Issue by Logout22** [jupp0r/prometheus-cpp#183]
Right now, the Registry is write-only: It has many AddSomething methods, but no way to retrieve a specific metric value. Should we add such functionality, e.g. being able to search for metrics by their attached labels?

**Comment by jupp0r** [comment]
Can you describe what you'd want to use it for? With the current design of the registry, I wanted to avoid people using a search mechanism because of the overhead it causes. Incrementing a counter is pretty fast, but searching for one in order to increment it is orders of magnitude slower. A workaround for you would be to create a `map<std::string, Counter&>` or similar yourself.

**Comment by Logout22** [comment]
I agree that with these kinds of run time penalties, we would need a distinct wrapper and documentation informing users about the differences.

Interest for such a wrapper seems to be rather low given that there was no feedback on the issue for several months, and I seem to recall that the problem I had initially is solved, so I am closing now.

Feel free to reopen. :)
