### ISSUE TITLE
Metric Add/Remove behavior

### ISSUE THREAD

**Issue by laoshanxi** [jupp0r/prometheus-cpp#328]
I create metric like bellow and I found the Family::Add(Counter) will check existance and return if already exist, 
```
auto& counter = prometheus::BuildCounter()
		.Name(metricName)
		.Help(metricHelp)
		.Register(*m_promRegistry)
		.Add(commonLabels);
return &counter;
```

And the Remove will do actually memory remove for Metric, is this correct?

metric name + labels should keep unique, is this correct?

Another consideration is that the Family::Add() function return a metric object reference but not shared_ptr, so when I used in my code, I should kept "prometheus:Counter*" to access for metric increase and release, this seems not safe. is there any better way for Add/Remove metric dynamic in code by a safe way (metric object memory management)?

Bellow is my project using this project, thanks for provide this library that make prometheus integration easily.
https://github.com/laoshanxi/app-manager/blob/master/src/daemon/PrometheusRest.cpp

Thanks very much.

**Comment by jupp0r** [comment]
> And the Remove will do actually memory remove for Metric, is this correct?

Yes

> Another consideration is that the Family::Add() function return a metric object reference but not shared_ptr, so when I used in my code, I should kept "prometheus:Counter*" to access for metric increase and release, this seems not safe. is there any better way for Add/Remove metric dynamic in code by a safe way (metric object memory management)?

The counter object is owned by the registry. A reference to the counter is returned by ‘Family::Add()’, and this is what you should save (‘Counter&’ instead of ‘Counter*’). References in C++ cannot be ‘nullptr’ and they can’t be deleted. With “not safe”, I assume you are referring to the reference dangling. If you are using ‘Remove()’ (which is an edge case anyway), you need to ensure that you are not interacting with the counter after you called remove. If you don’t use remove, it’s sufficient to ensure no metrics are used after the registry is deleted (usually by ensuring the registry is deleted late in the shutdown process). If you want to use ‘shared_ptr’, you could write wrapper object that holds the counter reference and calls Remove() in its destructor (make sure to make it non-copyable) and hold a shared_ptr to that object.

**Comment by laoshanxi** [comment]
Thanks for the quick reply.

‘Counter&’ can  nonly be used in construct function, but throw func in construction is not suggested, so the better way is use wrapper "shared_ptr".

Thanks so much.
