### ISSUE TITLE
Fix building on Windows

### ISSUE THREAD

**Issue by brechtsanders** [jupp0r/prometheus-cpp#401]
I just tried to build v0.10.0 on Windows with MinGW-w64 (from http://winlibs.com) under MSYS2 shell using CMake and Ninja and got this error:
```
CMake Error at pull/CMakeLists.txt:23 (add_library):
  Target "pull" links to target "WINSOCK::WINSOCK" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
```

The solution was to this to `pull/CMakeLists.txt `:
```
if(WIN32)
  add_library(WINSOCK::WINSOCK INTERFACE IMPORTED)
  target_link_libraries(WINSOCK::WINSOCK INTERFACE ws2_32)
endif()
```

I'm not sure if this is a general issue on Windows, or just MinGW(-w64). In the latter case you should probably use `if(MINGW)` instead.

**Comment by gjasny** [comment]
Thanks for reporting. I'll take a look.

**Comment by gjasny** [comment]
Hello,

the problem lies within [civetweb](https://github.com/civetweb/civetweb) and how it links against winsock. They use a `FindWinsock.cmake` and link against the imported `WINSOCK::WINSOCK` target. But they neither ship their Winsock find module nor do they look winsock up in the civetweb cmake config file.

I'll try to fix it in civetweb but it might some time until a fix is released.

What should work is the work-around you developed as well as linking against the embedded civetweb library (`-DUSE_THIRDPARTY_LIBRARIES=ON`)

Thanks,
Gregor

**Comment by gjasny** [comment]
I filed civetweb/civetweb#918 to fix the issue.
