### ISSUE TITLE
bug in presenting very high counters

### ISSUE THREAD

**Issue by galzafrany** [jupp0r/prometheus-cpp#416]
when a some counter metrics reach high values i get some enormous jump in the http server, in several magnitudes higher then the value i pass. 14 digits number in my app turns into 20 digit number in http server.
is this a know issue?

**Comment by gjasny** [comment]
Could you please share an example?

**Comment by galzafrany** [comment]
yes:
my app measures number of bits with some inner uint64_t counter, and after casting it to double, i pass it to the 3rd party methods. when the counter itself reaches somewhere around 4*10^14, i see a different value in the http server, much bigger. something around 3*10^19, which exceeds the limit of a unsigned 64 bit integer. This happens occasionally, and not in all instances of the app, which makes it even more weird.

**Comment by gjasny** [comment]
Hello,

I believe you're observing errors due to how doubles are represented: [Double-precision floating-point format](https://en.wikipedia.org/wiki/Double-precision_floating-point_format). With doubles you could only represent 15 decimal digits: https://godbolt.org/z/Tdox7x

One option to bump the limit to 18 digits (on Unix only) is using `long doubles` instead. But I could imagine that processing which happens later down in the chain (influx, grafana) might suffer from the same processing problems.

What are you observing? Your number represents the full DE-CIX internet-traffic throughput for 9 months.

Also bserving whole bytes would extend the limit by 8 times.

Thanks,
Gregor

**Comment by gjasny** [comment]
I made a branch where you could replace the floating point type: https://github.com/jupp0r/prometheus-cpp/blob/value-type/core/include/prometheus/detail/value_type.h#L7

**Comment by galzafrany** [comment]
But how does it work out with the fact that i get 20 digits double? all my app's counters (which are used as metric of type counter) are uint64_t so i don't have a need in some floating/fixed point accuracy from the first place. Is there a way to export counters as long or to set 0 precision only to counter metrics?

**Comment by gjasny** [comment]
Instead of a Counter you could use a Gauge and call set(value) directly.

**Comment by galzafrany** [comment]
i dont see that fix in the new version 0.11.0

**Comment by gjasny** [comment]
Where do you store your metrics? In Influx or Prometheus ( or somewhere else)?

**Comment by galzafrany** [comment]
Prometheus

**Comment by gjasny** [comment]
The prometheus [exposition formats](https://github.com/prometheus/docs/blob/main/content/docs/instrumenting/exposition_formats.md) clearly states that the values must be parseable by Go's `ParseFloat()` which returns a `float64`. Increasing the float type in prometheus won't help if later consumers cannot handle the width.
