### ISSUE TITLE
Thread safety?

### ISSUE THREAD

**Issue by jdx-john** [jupp0r/prometheus-cpp#450]
I've run into weird issues which I think might be threading-related. I have `CMyClass` which builds some metrics and works fine. In a more advanced application, multiple instances of `CMyClass` are created and as soon as the 2nd one is created, something goes wrong... an uncaught exception during initialization (which is where my prometheus code is).

I haven't been able to debug it yet as I only have access to a remote system, so can you advise if there are any known issues with thread safety or object duplication? I utilise a standard C++ singleton to wrap the following instances, which are initialised in the singleton-ctor:

```
	std::unique_ptr<prometheus::Exposer> m_pExposer;
	std::shared_ptr<prometheus::Registry> m_pRegistry;

```

**Comment by jupp0r** [comment]
It's hard to say what's going wrong without seeing your code, a stack trace or at least the exception.

Interacting with metrics in the registry is thread safe, adding new metrics to the registry is not. If multiple threads are accessing the registry, you need to protect it with a mutex. If you create multiple exposers that could cause problems because they might want to bind to the same port.

Hope that helps,

Jupp

**Comment by jdx-john** [comment]
@jupp0r trying to identify/isolate in order to find some code I might post, thought I'd check for known 'gotchas' first. Essentially each instance in it's ctor is doing:

	auto& m = BuildGauge()
		.Name("my_metric")
		.Add({ {"subsystem",this->GetSubsystemName()} }
                 .Register(*registry);

I already checked that prometheus-cpp coalesces (merges) different label-dimensions of the same family - which is a nice feature in the library.

I shall check further, if it is a thread issue or something else.
