### ISSUE TITLE
import static library, make error

### ISSUE THREAD

**Issue by guojun08512** [jupp0r/prometheus-cpp#461]
-- The CXX compiler identification is GNU 7.5.0
../../thirdparty/install/lib/libprometheus-cpp-pull.a(handler.cc.o): In function `prometheus::detail::MetricsHandler::handleGet(CivetServer*, mg_connection*)':
handler.cc:(.text+0x17f8): undefined reference to `vtable for prometheus::TextSerializer'
handler.cc:(.text+0x180d): undefined reference to `prometheus::Serializer::Serialize[abi:cxx11](std::vector<prometheus::MetricFamily, std::allocator<prometheus::MetricFamily> > const&) const'

but so is ok

**Comment by gjasny** [comment]
It's probably the linking order. Please try avoiding these problems altogether by importing the prometheus CMake targets as it is done here:
https://github.com/jupp0r/prometheus-cpp/blob/77a5b0172833786ec014498d61a4dd87c500dc3b/cmake/project-import-cmake/CMakeLists.txt#L7-L17

Otherwise take a look here:
https://github.com/jupp0r/prometheus-cpp#plain-makefiles

**Comment by guojun08512** [comment]
I import lib order mistake, thank you.
