### ISSUE TITLE
Could you release a version of VS2019 supported binary?

### ISSUE THREAD

**Issue by 13818326024** [jupp0r/prometheus-cpp#465]
It is hardly compiled and I can not find any release version. Could you release a version of it and send it to my email 195378366@qq.com.
Thanks very much.

**Comment by gjasny** [comment]
Hallo,

if you have troubles compiling this library you might find a package manager like vcpkg or conan useful. They not only handle the prometheus-cpp library itself but also its dependencies like zlib (or if needed libcurl).

We intentionally do not ship binaries because the permutations of the configuration is pretty huge. There could be
* DLL or static library
* dynamic or static runtime
* unicode / no unicode
* SSL or no ssl support
* zlib or no zlib support
* different visual studio versions
* embeded or external civetweb

Thanks for understanding,
-Gregor
