### ISSUE TITLE
google/protobuf should be submodule

### ISSUE THREAD

**Issue by marcpawl** [jupp0r/prometheus-cpp#48]
On some platforms, CentOs, the version of googlebuf is much older than is needed to compile.
In particular google/protobuf/util is not installed.

**Comment by jupp0r** [comment]
I agree that it's a big pain point (I'm currently using this on RHEL6 at work). I opted against the submodule solution for protobuf, because otherwise ABI compatibiliy issues would force all consumers of `prometheus-cpp` to use exactly the same protobuf version as the one inside the submodule if they were using protobuf itself.

To phrase it differently, this library should not control the exact version, but the binary built from it should determine a version that all libraries link against.

Makes sense?
