### ISSUE TITLE
A C++ 14 compiler is required.

### ISSUE THREAD

**Issue by Hallot** [jupp0r/prometheus-cpp#610]
According to the readme, only a C++11 compiler is required, but `std::make_unique`, a C++ 14 feature, is used in https://github.com/jupp0r/prometheus-cpp/blob/master/core/include/prometheus/family.h#L113

When trying to build with Bazel on MacOS ARM, the build fails with:
```
bazel-out/darwin_arm64-fastbuild/bin/core/_virtual_includes/core/prometheus/family.h:113:29: error: no member named 'make_unique' in namespace 'std'
    return Add(labels, std::make_unique<T>(args...));
                       ~~~~~^
```
Presumably because no C++ standard is set and Bazel defaults to C++11 (I guess?).
It works with CMake, presumably because recent Clangs default to C++14.

**Comment by gjasny** [comment]
It works in CI due to the `--cxxopt` passed:
https://github.com/jupp0r/prometheus-cpp/blob/2a1246f6eb30f6d4dc608f59c1af0a2e49c9b704/.github/workflows/bazel-ci.yml#L12-L17

Unfortunately I cannot default to anything because those differ between Unix and Windows.

I'll update the documentation about the C++14 requirement.

**Comment by Hallot** [comment]
Thanks!
