### ISSUE TITLE
Is is possible to listen on current port of my service?

### ISSUE THREAD

**Issue by nghiavt1001** [jupp0r/prometheus-cpp#627]
Hi,
I need to integrate this library to my service which handle list of API on port 9096. However, I do not want to create a new port for prometheus, is it possible to config for prometheus listening at port 9096 so I could get metrics at http://127.0.0.1:9096/metrics?
Thank you!

**Comment by gjasny** [comment]
Yes, that should not be too complicated. Please have a look at `MetricsHandler::handleGet`. You require basically need the following lines: https://github.com/jupp0r/prometheus-cpp/blob/81e208c250748657f1d5dab247e82c4429a931af/pull/src/handler.cc#L145-L154

I will move the `CollectMetrics` utility into the core library so that you'll only have to link against this one.

**Comment by nghiavt1001** [comment]
Thank you, problem solved!
