### ISSUE TITLE
/metrics data format looks strange

### ISSUE THREAD

**Issue by baiwfg2** [jupp0r/prometheus-cpp#68]
Hi, jupp0r. when using prometheus-cpp, visit page localhost:9090/metrics, I got the following data format:

> name: "exposer_bytes_transfered"
> help: "bytesTransferred to metrics services"
> type: COUNTER
> metric {
>   counter {
>     value: 326609664
>   }
> }
> 
> name: "exposer_total_scrapes"
> help: "Number of times metrics were scraped"
> type: COUNTER
> metric {
>   counter {
>     value: 116818
>   }
> }
> 
> name: "exposer_request_latencies"
> help: "Latencies of serving scrape requests, in milliseconds"
> type: HISTOGRAM
> metric {
>   histogram {
>     sample_count: 116818
>     sample_sum: 1332
>     bucket {
>       cumulative_count: 115487
>       upper_bound: 1
>     }

But I found many prometheus exporters don't show data like this. Here's the redis-exporter case:

> \# HELP a1_aof_rewrite_scheduled 
> \# TYPE a1_aof_rewrite_scheduled gauge
> a1_aof_rewrite_scheduled{addr="localhost:30001",alias=""} 0
> \# HELP a1_blocked_clients 
> \# TYPE a1_blocked_clients gauge
> a1_blocked_clients{addr="localhost:30001",alias=""} 0
> \# HELP a1_cluster_current_epoch 
> \# TYPE a1_cluster_current_epoch gauge
> a1_cluster_current_epoch{addr="localhost:30001",alias=""} 6
> \# HELP a1_cluster_enabled 
> \# TYPE a1_cluster_enabled gauge
> a1_cluster_enabled{addr="localhost:30001",alias=""} 1
> \# HELP a1_cluster_known_nodes 
> \# TYPE a1_cluster_known_nodes gauge
> a1_cluster_known_nodes{addr="localhost:30001",alias=""} 6

why is that ? Seems prometheus 2.0 cannot identify the first format when upgrading from prometheus 1.x to 2.0. Error shows:

> strconv.ParseFloat: parsing "\"exposer_bytes_transfered\"": invalid syntax

So how should I change my code to use the second format ? Thanks.

**Comment by jupp0r** [comment]
Prometheus-cpp currently only supports the protobuf format for metrics. This is usually negotiated via Content-Type negotiation on the scrape request (that's why it works for prometheus 1.x). There is an open issue (#9) to implement the text format. For now, accessing the `/metrics` url without requesting the protobuf format merely prints out the `Metrics` protobuf struct via protobufs `DebugString()` facility in order to have something human-readable.

I'll investigate why prometheus 2.0 does not support the protobuf encoding anymore.

Would you be willing to help with #9 ?

**Comment by baiwfg2** [comment]
I see. I'll track the issue. Thank you.

**Comment by jupp0r** [comment]
Ok, it seems like prometheus 2.0 might drop protobuf format support altogether (still undecided, see https://github.com/prometheus/prometheus/issues/2788).

**Comment by jupp0r** [comment]
Resolved because we have text format support now
