### ISSUE TITLE
Family::Add function should check for existing metric

### ISSUE THREAD

**Issue by mikea** [jupp0r/prometheus-cpp#75]
Without `Add` function doing existing labels check, it is very inconvenient to work with dynamic label values. I have to introduce a map myself and keep track of created counters. Instead it will be trivial for Family to check.

**Comment by jupp0r** [comment]
Do you think throwing would be appropriate in that situation?

**Comment by mfontanini** [comment]
I've had to do this in my code as well. The ideal solution would be if `Family::Add` checked if there's already a metric with those labels and if it does exist, then it returns the existing metric. Right now the code is very broken if you call `Add` with the same labels twice as you'll be returning a reference to an already deleted pointer (`unique_ptr` deletes it right away as the `insert` will fail due to the element already being there).

**Comment by jupp0r** [comment]
That makes sense, I just wonder if it might be better to not silently ignore the double add, but trigger something that reveals it to the user.

**Comment by mikea** [comment]
@jupp0r @mfontanini correctly handling is way, way better than revealing to the user. Why would you like to throw?

**Comment by jupp0r** [comment]
I just thought that it might be nice to realize you are double-adding a metric, which you might consider a logic error in your code. I don't prefer throwing, I just wanted to include that as an option in the discussion we are having :) Personally, I actually prefer just returning the existing metric.

**Comment by mikea** [comment]
> Personally, I actually prefer just returning the existing metric.

+100 to that. 

> which you might consider a logic error in your code

I can hardly imagine a situation when returning the existing metrics is not what use wants.

**Comment by jupp0r** [comment]
Thanks for the input, returning the existing metric it is, then.

**Comment by mikea** [comment]
PR: https://github.com/jupp0r/prometheus-cpp/pull/76

**Comment by mikea** [comment]
this is fixed.
